version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGOPORT=27017
      - DATABASE_URL=${DATABASE_URL}
      - MONGODB_URI=${MONGODB_URI}
      - API_KEY=${API_KEY}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge